-- CBC x SOLved · esquema canónico de acceso granular
-- Aplicar en Supabase después de revisar contra la base real. max_unit se conserva sólo por compatibilidad.
create table if not exists public.access_profiles (
  email text primary key,
  max_unit integer not null default 1 check (max_unit between 1 and 13),
  active boolean not null default true,
  role text not null default 'student' check (role in ('student','tester','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  access_starts_at timestamptz not null default now(),
  access_expires_at timestamptz
);
alter table public.access_profiles add column if not exists access_starts_at timestamptz not null default now();
alter table public.access_profiles add column if not exists access_expires_at timestamptz;
create table if not exists public.access_grants (
  email text not null references public.access_profiles(email) on update cascade on delete cascade,
  subject text not null default 'chemistry',
  unit_no integer not null check (unit_no between 1 and 13),
  grant_type text not null check (grant_type in ('unit','chapter','guide','practice','evaluation','partial','resource')),
  grant_key text not null default '*',
  created_at timestamptz not null default now(),
  primary key (email,subject,unit_no,grant_type,grant_key)
);
create table if not exists public.course_sections (
  id bigint generated by default as identity primary key,
  subject text not null, unit_no integer not null check (unit_no between 1 and 13),
  section_key text not null, section_type text not null, title text not null,
  sort_order integer not null default 0, body_html text not null default '',
  is_public boolean not null default false, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(), unique(subject,unit_no,section_key)
);
alter table public.access_profiles enable row level security;
alter table public.access_grants enable row level security;
alter table public.course_sections enable row level security;
create or replace function public.is_cbc_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select lower(coalesce(auth.jwt()->>'email',''))='clasesbysol@gmail.com' $$;
create or replace function public.has_active_cbc_access(target_subject text,target_unit integer,target_type text,target_key text)
returns boolean language sql stable security definer set search_path=public
as $$
  select public.is_cbc_admin() or exists(
    select 1 from public.access_profiles p join public.access_grants g on lower(g.email)=lower(p.email)
    where lower(p.email)=lower(coalesce(auth.jwt()->>'email','')) and p.active
      and now()>=p.access_starts_at and (p.access_expires_at is null or now()<=p.access_expires_at)
      and g.subject=target_subject and g.unit_no=target_unit
      and ((g.grant_type='unit' and g.grant_key='*') or (g.grant_type=target_type and g.grant_key=target_key))
  )
$$;
drop policy if exists "read own access" on public.access_profiles;
drop policy if exists "admin insert access" on public.access_profiles;
drop policy if exists "admin update access" on public.access_profiles;
drop policy if exists "admin delete access" on public.access_profiles;
create policy "read own access" on public.access_profiles for select to authenticated using(lower(email)=lower(coalesce(auth.jwt()->>'email','')) or public.is_cbc_admin());
create policy "admin insert access" on public.access_profiles for insert to authenticated with check(public.is_cbc_admin());
create policy "admin update access" on public.access_profiles for update to authenticated using(public.is_cbc_admin()) with check(public.is_cbc_admin());
create policy "admin delete access" on public.access_profiles for delete to authenticated using(public.is_cbc_admin());
drop policy if exists "read own grants" on public.access_grants;
drop policy if exists "admin insert grants" on public.access_grants;
drop policy if exists "admin update grants" on public.access_grants;
drop policy if exists "admin delete grants" on public.access_grants;
create policy "read own grants" on public.access_grants for select to authenticated using(lower(email)=lower(coalesce(auth.jwt()->>'email','')) or public.is_cbc_admin());
create policy "admin insert grants" on public.access_grants for insert to authenticated with check(public.is_cbc_admin());
create policy "admin update grants" on public.access_grants for update to authenticated using(public.is_cbc_admin()) with check(public.is_cbc_admin());
create policy "admin delete grants" on public.access_grants for delete to authenticated using(public.is_cbc_admin());
drop policy if exists "read allowed course sections" on public.course_sections;
drop policy if exists "admin manage course sections" on public.course_sections;
create policy "read allowed course sections" on public.course_sections for select to anon,authenticated
  using(is_public or public.has_active_cbc_access(subject,unit_no,section_type,section_key));
create policy "admin manage course sections" on public.course_sections for all to authenticated using(public.is_cbc_admin()) with check(public.is_cbc_admin());
update public.course_sections set is_public=true where subject='chemistry' and unit_no=1 and is_public is distinct from true;
create index if not exists access_grants_lookup_idx on public.access_grants(lower(email),subject,unit_no,grant_type,grant_key);
create index if not exists course_sections_lookup_idx on public.course_sections(subject,unit_no,section_type,section_key,is_public);

-- Ejercicios y soluciones protegidas.
-- Exercise statements and protected solutions for CBC x SOLved.
create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  subject text not null default 'chemistry',
  unit_no integer not null check (unit_no between 1 and 13),
  section_key text not null,
  title text not null,
  statement_html text not null,
  source_label text,
  sort_order integer not null default 0,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(subject,unit_no,section_key,title)
);
create table if not exists public.exercise_solutions (
  exercise_id bigint primary key references public.exercises(id) on delete cascade,
  solution_html text not null,
  final_answer text,
  student_visible boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.exercises enable row level security;
alter table public.exercise_solutions enable row level security;

create or replace function public.can_access_exercise(target_id bigint)
returns boolean language sql stable security definer set search_path=public
as $$
 select public.is_cbc_admin() or exists(
   select 1 from public.exercises e
   where e.id=target_id and (
     e.is_public or public.has_active_cbc_access(e.subject,e.unit_no,'exercise',e.section_key)
     or public.has_active_cbc_access(e.subject,e.unit_no,'chapter',e.section_key)
   )
 )
$$;

drop policy if exists "read allowed exercises" on public.exercises;
drop policy if exists "admin manage exercises" on public.exercises;
create policy "read allowed exercises" on public.exercises for select to anon,authenticated
 using(is_public or public.has_active_cbc_access(subject,unit_no,'exercise',section_key)
   or public.has_active_cbc_access(subject,unit_no,'chapter',section_key));
create policy "admin manage exercises" on public.exercises for all to authenticated
 using(public.is_cbc_admin()) with check(public.is_cbc_admin());

drop policy if exists "read visible solutions" on public.exercise_solutions;
drop policy if exists "admin manage solutions" on public.exercise_solutions;
create policy "read visible solutions" on public.exercise_solutions for select to anon,authenticated
 using(public.is_cbc_admin() or (student_visible and public.can_access_exercise(exercise_id)));
create policy "admin manage solutions" on public.exercise_solutions for all to authenticated
 using(public.is_cbc_admin()) with check(public.is_cbc_admin());

create index if not exists exercises_lookup_idx on public.exercises(subject,unit_no,section_key,is_public,sort_order);
create index if not exists solutions_visibility_idx on public.exercise_solutions(student_visible,exercise_id);




