-- CBC x SOLved · Supabase v0.1.0
create table if not exists public.access_profiles (
  email text primary key,
  max_unit integer not null default 1 check (max_unit between 1 and 13),
  active boolean not null default true,
  role text not null default 'student' check (role in ('student','tester','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.unit_previews (
  id bigint generated by default as identity primary key,
  subject text not null default 'chemistry',
  unit_no integer not null check (unit_no between 1 and 13),
  sort_order integer not null default 0,
  title text not null,
  body_html text not null default ''
);
create table if not exists public.unit_content (
  id bigint generated by default as identity primary key,
  subject text not null default 'chemistry',
  unit_no integer not null check (unit_no between 1 and 13),
  section_key text not null,
  sort_order integer not null default 0,
  title text not null,
  body_html text not null default '',
  unique(subject,unit_no,section_key)
);
alter table public.access_profiles enable row level security;
alter table public.unit_previews enable row level security;
alter table public.unit_content enable row level security;
create or replace function public.is_cbc_admin() returns boolean language sql stable security definer set search_path=public as $$ select lower(coalesce(auth.jwt()->>'email',''))='clasesbysol@gmail.com'; $$;
create or replace function public.can_access_chemistry_unit(requested_unit integer) returns boolean language sql stable security definer set search_path=public as $$ select requested_unit=1 or public.is_cbc_admin() or exists(select 1 from public.access_profiles p where lower(p.email)=lower(coalesce(auth.jwt()->>'email','')) and p.active=true and p.max_unit>=requested_unit); $$;
drop policy if exists "read own access" on public.access_profiles;
create policy "read own access" on public.access_profiles for select to authenticated using(lower(email)=lower(coalesce(auth.jwt()->>'email','')) or public.is_cbc_admin());
drop policy if exists "admin insert access" on public.access_profiles;
create policy "admin insert access" on public.access_profiles for insert to authenticated with check(public.is_cbc_admin());
drop policy if exists "admin update access" on public.access_profiles;
create policy "admin update access" on public.access_profiles for update to authenticated using(public.is_cbc_admin()) with check(public.is_cbc_admin());
drop policy if exists "admin delete access" on public.access_profiles;
create policy "admin delete access" on public.access_profiles for delete to authenticated using(public.is_cbc_admin());
drop policy if exists "public previews" on public.unit_previews;
create policy "public previews" on public.unit_previews for select to anon,authenticated using(true);
drop policy if exists "admin previews" on public.unit_previews;
create policy "admin previews" on public.unit_previews for all to authenticated using(public.is_cbc_admin()) with check(public.is_cbc_admin());
drop policy if exists "allowed content" on public.unit_content;
create policy "allowed content" on public.unit_content for select to anon,authenticated using(subject='chemistry' and public.can_access_chemistry_unit(unit_no));
drop policy if exists "admin content" on public.unit_content;
create policy "admin content" on public.unit_content for all to authenticated using(public.is_cbc_admin()) with check(public.is_cbc_admin());
