const CFG=window.CBCLASES_CONFIG||{};
const UNITS=[...Array(13)].map((_,i)=>i+1);
let sb=null,session=null,guest=localStorage.getItem('cbc-mode')==='guest',view='subjects',unit=1,side=false,search=false,theme=false,installPrompt=null,msg='';
let access={max_unit:1,active:true,role:'student'},rows=[];
let accent=localStorage.getItem('cbc-accent')||'#0f9f9a';
document.documentElement.style.setProperty('--accent',accent);
const app=document.querySelector('#app');
const configured=()=>Boolean(CFG.supabaseUrl&&CFG.supabaseAnonKey);
const mail=()=>String(session?.user?.email||'').toLowerCase();
const isAdmin=()=>mail()&&mail()===String(CFG.adminEmail||'').toLowerCase();
const maxUnit=()=>guest?1:isAdmin()?13:(access.active?Number(access.max_unit||1):0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

async function init(){
 if(configured()){
  const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');
  sb=createClient(CFG.supabaseUrl,CFG.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  session=(await sb.auth.getSession()).data.session;
  if(session){guest=false;localStorage.setItem('cbc-mode','account');await loadOwnAccess();}
  sb.auth.onAuthStateChange(async(_,next)=>{session=next;if(next){guest=false;localStorage.setItem('cbc-mode','account');await loadOwnAccess();}render();});
 }
 render();
}
async function loadOwnAccess(){
 if(!sb||!session)return;
 if(isAdmin()){access={max_unit:13,active:true,role:'admin'};return;}
 const {data}=await sb.from('access_profiles').select('email,max_unit,active,role').eq('email',mail()).maybeSingle();
 access=data||{max_unit:1,active:false,role:'student'};
}
async function google(){
 if(!configured()||!sb){msg='El ingreso con Gmail queda listo apenas conectemos Supabase. La navegación como invitado ya funciona.';render();return;}
 await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}${location.pathname}`}});
}
async function logout(){if(sb&&session)await sb.auth.signOut();session=null;guest=false;access={max_unit:1,active:true,role:'student'};localStorage.removeItem('cbc-mode');view='subjects';render();}
async function loadRows(){if(!sb||!isAdmin())return;const {data}=await sb.from('access_profiles').select('email,max_unit,active,role').order('email');rows=data||[];}
async function addAccess(){const email=document.querySelector('#newEmail')?.value.trim().toLowerCase();const max_unit=Number(document.querySelector('#newMax')?.value||1);if(!email)return;if(!sb){msg='Modo maqueta: conectá Supabase para guardar accesos reales.';rows=[...rows.filter(r=>r.email!==email),{email,max_unit,active:true,role:'student'}];render();return;}await sb.from('access_profiles').upsert({email,max_unit,active:true,role:'student'},{onConflict:'email'});await loadRows();render();}
async function patchAccess(email,patch){rows=rows.map(r=>r.email===email?{...r,...patch}:r);render();if(sb){await sb.from('access_profiles').update(patch).eq('email',email);await loadRows();render();}}

function brand(){return `<div class="brand"><img src="./sun.svg" class="brandSun" alt=""><div><b>CBC x SOLved</b><small>Clases y estudio del CBC</small></div></div>`;}
function welcome(){return `<main class="welcomeShell"><section class="welcomeCard">${brand()}<div class="welcomeCopy"><span class="eyebrow">Tu espacio de estudio del CBC</span><h1>Entrá, elegí materia y estudiá sin vueltas.</h1><p>Química empieza acá. Matemática ya tiene su lugar preparado para después.</p></div><div class="welcomeActions"><button class="primaryButton" data-a="google">G&nbsp;&nbsp;Ingresar con Gmail</button><button class="secondaryButton" data-a="guest">☀️ Ver como invitado</button><button class="ghostButton" data-a="install">↓ Instalar app</button></div>${msg?`<div class="statusNote">${esc(msg)}</div>`:''}<div class="welcomeFine">Después del primer ingreso, la sesión queda guardada en este dispositivo hasta que cierres sesión.</div></section></main>`;}
function navButton(v,label,icon){return `<button data-v="${v}" class="${view===v||(v==='chemistry'&&view==='unit')?'active':''}"><span>${icon}</span>${label}</button>`;}
function sidebar(){return `<aside class="sidebar ${side?'open':''}"><div class="sidebarTop">${brand()}<button class="iconButton mobileOnly" data-a="closeSide">×</button></div><nav class="navList">${navButton('subjects','Materias','⌂')}${navButton('chemistry','Química','⚗')}${navButton('math','Matemática','Σ')}${isAdmin()?navButton('admin','Accesos','👤'):''}</nav><div class="unitIndex"><div class="sideLabel">Índice · Química</div>${UNITS.map(u=>`<button data-u="${u}" class="${view==='unit'&&unit===u?'activeUnit':''}"><span>${u}</span><div>Unidad ${u}</div><b>${u>maxUnit()?'🔒':''}</b></button>`).join('')}</div><div class="sidebarBottom"><button data-a="theme">◉ Apariencia</button><button data-a="logout">↪ ${guest?'Salir de invitado':'Cerrar sesión'}</button></div></aside>${side?'<button class="backdrop" data-a="closeSide"></button>':''}`;}
function top(){const title=view==='subjects'?'Materias':view==='chemistry'?'Química':view==='math'?'Matemática':view==='admin'?'Accesos':`Química · Unidad ${unit}`;const pill=guest?'Invitado':isAdmin()?'Admin':maxUnit()?`Hasta U${maxUnit()}`:'Suspendido';return `<header class="topbar"><button class="iconButton" data-a="openSide">☰</button><b>${title}</b><div class="topbarActions"><button class="iconButton" data-a="search">⌕</button><span class="accessPill">${pill}</span></div></header>`;}
function subjects(){return `<section class="heroBlock"><span class="eyebrow">CBC x SOLved</span><h1>¿Qué querés estudiar hoy?</h1><p>Elegí una materia.</p></section><section class="subjectGrid"><button class="subjectCard" data-v="chemistry"><div class="subjectIcon">⚗</div><div><span class="cardKicker">Disponible</span><h2>Química</h2><p>13 unidades preparadas para teoría, ejercicios y parciales.</p></div><b>›</b></button><button class="subjectCard math" data-v="math"><div class="subjectIcon">Σ</div><div><span class="cardKicker muted">Próximamente</span><h2>Matemática</h2><p>Espacio reservado. Todavía sin contenido.</p></div><b>›</b></button></section>`;}
function chemistry(){const intro=guest?'Como invitado tenés la Unidad 1 y una pequeña vista previa del resto.':`Tu acceso actual llega hasta la Unidad ${maxUnit()}.`;return `<section class="heroBlock compactHero"><span class="eyebrow">Química CBC</span><h1>13 unidades, una sola ruta.</h1><p>${intro}</p></section><section class="unitGrid">${UNITS.map(u=>{const ok=u<=maxUnit();return `<button class="unitCard ${ok?'':'locked'}" data-u="${u}"><div class="unitNumber">${String(u).padStart(2,'0')}</div><div class="unitText"><span>${ok?'Disponible':'Vista previa'}</span><h3>Unidad ${u}</h3><p>Contenido listo para incorporar.</p></div><div class="unitState">${ok?'☀':'🔒'}</div></button>`}).join('')}</section>`;}
function unitPage(){if(unit>maxUnit())return `<section class="lockedPage"><div class="lockOrb">🔒</div><span class="eyebrow">Unidad ${unit}</span><h1>Una pequeña muestra de esta unidad.</h1><p>Acá va a aparecer una introducción breve para que el invitado vea el estilo del material antes de acceder al contenido completo.</p><div class="teaser"><b>Vista previa</b><div class="fakeLine wide"></div><div class="fakeLine"></div><div class="fakeLine short"></div></div><div class="paywallNote">El desarrollo completo se habilita según el acceso asignado a tu mail.</div></section>`;return `<section class="unitPage"><span class="eyebrow">Química CBC · Unidad ${unit}</span><h1>Unidad ${unit}</h1><p class="lead">La estructura está lista. En la próxima etapa cargamos los PDFs de esta unidad.</p><div class="contentSkeleton"><div><span>01</span><strong>Teoría</strong><p>Diapositivas y explicación integrada.</p></div><div><span>02</span><strong>Ejercitación</strong><p>Guías completas y resolución paso a paso.</p></div><div><span>03</span><strong>Parciales</strong><p>Modelos y criterios de resolución.</p></div><div><span>04</span><strong>Glosario</strong><p>Conceptos importantes de la unidad.</p></div></div>${guest&&unit===1?'<div class="guestBadge">Unidad 1 habilitada para invitados</div>':''}</section>`;}
function math(){return `<section class="emptySubject"><div class="subjectIcon big">Σ</div><span class="eyebrow">Matemática CBC</span><h1>El lugar ya está reservado.</h1><p>Por ahora no vamos a cargar contenido acá.</p></section>`;}
function admin(){return `<section class="heroBlock compactHero"><span class="eyebrow">Administración</span><h1>Accesos de alumnos</h1><p>Agregá un mail y elegí hasta qué unidad puede entrar.</p></section>${!configured()?'<div class="demoBanner">Modo maqueta: falta conectar Supabase para persistir cambios.</div>':''}<section class="adminCard"><div class="addAccessRow"><label>Email<input id="newEmail" type="email" placeholder="alumno@gmail.com"></label><label>Acceso hasta<select id="newMax">${UNITS.map(u=>`<option value="${u}">Unidad ${u}</option>`).join('')}</select></label><button class="primaryButton small" data-a="addAccess">Agregar</button></div><div class="accessTableWrap"><table class="accessTable"><thead><tr><th>Mail</th><th>Hasta</th><th>Estado</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td><b>${esc(r.email)}</b></td><td><select data-mail="${esc(r.email)}">${UNITS.map(u=>`<option value="${u}" ${Number(r.max_unit)===u?'selected':''}>Unidad ${u}</option>`).join('')}</select></td><td><button class="statusToggle ${r.active?'on':'off'}" data-toggle="${esc(r.email)}">${r.active?'Activo':'Suspendido'}</button></td></tr>`).join(''):'<tr><td colspan="3" class="emptyTable">Todavía no hay accesos cargados.</td></tr>'}</tbody></table></div></section>`;}
function searchModal(){return `<div class="modalLayer"><div class="searchModal"><div class="searchBox">⌕<input id="q" autofocus placeholder="Buscar materia o unidad…"><button class="iconButton" data-a="closeSearch">×</button></div><div id="results" class="searchResults"><div class="emptySearch">Escribí para buscar dentro de CBC x SOLved.</div></div></div></div>`;}
function themeModal(){return `<div class="modalLayer"><div class="themeModal"><div class="modalTitle"><div><span class="eyebrow">Apariencia</span><h3>Elegí tu turquesa</h3></div><button class="iconButton" data-a="closeTheme">×</button></div><div class="themeGrid">${[['Turquesa','#0f9f9a'],['Aqua','#0d9488'],['Cian','#0891b2'],['Menta','#16a394']].map(([n,c])=>`<button data-color="${c}"><span style="background:${c}"></span>${n}</button>`).join('')}</div><label class="customColor">Color personalizado <input id="custom" type="color" value="${accent}"></label></div></div>`;}
function render(){if(!session&&!guest){app.className='';app.innerHTML=welcome();bind();return;}let content=subjects();if(view==='chemistry')content=chemistry();if(view==='unit')content=unitPage();if(view==='math')content=math();if(view==='admin'&&isAdmin())content=admin();app.className='appShell';app.innerHTML=`${sidebar()}<div class="mainArea">${top()}<main class="content">${content}</main></div>${search?searchModal():''}${theme?themeModal():''}`;bind();}
function bind(){document.querySelectorAll('[data-v]').forEach(x=>x.onclick=async()=>{view=x.dataset.v;side=false;if(view==='admin')await loadRows();render();});document.querySelectorAll('[data-u]').forEach(x=>x.onclick=()=>{unit=Number(x.dataset.u);view='unit';side=false;render();});const on=(q,fn)=>{const x=document.querySelector(q);if(x)x.onclick=fn};on('[data-a="google"]',google);on('[data-a="guest"]',()=>{guest=true;localStorage.setItem('cbc-mode','guest');render()});on('[data-a="install"]',async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else{msg='En Chrome: menú ⋮ → Instalar app o Agregar a pantalla principal.';render()}});on('[data-a="logout"]',logout);on('[data-a="openSide"]',()=>{side=true;render()});document.querySelectorAll('[data-a="closeSide"]').forEach(x=>x.onclick=()=>{side=false;render()});on('[data-a="search"]',()=>{search=true;render();setTimeout(()=>document.querySelector('#q')?.focus(),0)});on('[data-a="closeSearch"]',()=>{search=false;render()});on('[data-a="theme"]',()=>{theme=true;render()});on('[data-a="closeTheme"]',()=>{theme=false;render()});on('[data-a="addAccess"]',addAccess);document.querySelectorAll('[data-mail]').forEach(x=>x.onchange=()=>patchAccess(x.dataset.mail,{max_unit:Number(x.value)}));document.querySelectorAll('[data-toggle]').forEach(x=>x.onclick=()=>{const r=rows.find(r=>r.email===x.dataset.toggle);if(r)patchAccess(r.email,{active:!r.active})});document.querySelectorAll('[data-color]').forEach(x=>x.onclick=()=>setAccent(x.dataset.color));const custom=document.querySelector('#custom');if(custom)custom.oninput=e=>setAccent(e.target.value);const q=document.querySelector('#q');if(q)q.oninput=e=>{const s=e.target.value.toLowerCase().trim();const data=[['Química','chemistry'],['Matemática','math'],...UNITS.map(u=>[`Química · Unidad ${u}`,`unit:${u}`])].filter(([t])=>t.toLowerCase().includes(s));document.querySelector('#results').innerHTML=s?(data.length?data.map(([t,k])=>`<button data-result="${k}"><b>${t}</b><span>›</span></button>`).join(''):'<div class="emptySearch">No encontré resultados.</div>'):'<div class="emptySearch">Escribí para buscar dentro de CBC x SOLved.</div>';document.querySelectorAll('[data-result]').forEach(r=>r.onclick=()=>{const k=r.dataset.result;if(k.startsWith('unit:')){unit=Number(k.split(':')[1]);view='unit'}else view=k;search=false;render()})};}
function setAccent(c){accent=c;localStorage.setItem('cbc-accent',c);document.documentElement.style.setProperty('--accent',c);render();}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
init().catch(e=>{console.error(e);msg='No se pudo iniciar el servicio de acceso. El modo invitado sigue disponible.';render();});
