-- Ampliación didáctica de Química CBC · Unidad 4.
-- Conserva las consignas de ejercicios sin cambios y suma teoría explicativa con palabras clave destacadas.
begin;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-01"><h3>Qué cuenta como dominio y por qué</h3><p>La <strong>TRePEV</strong> parte de una idea geométrica: las regiones de alta densidad electrónica alrededor del átomo central se acomodan de modo que la <strong>repulsión sea mínima</strong>. Un enlace simple, doble o triple ocupa una sola dirección alrededor del átomo central y por eso cuenta como <strong>un dominio electrónico</strong>. Cada par libre también cuenta como un dominio.</p><p>Hay que distinguir <strong>geometría electrónica</strong> de <strong>geometría molecular</strong>. La primera considera todos los dominios, incluidos los pares libres; la segunda describe únicamente la posición de los átomos. Por ejemplo, NH₃ tiene cuatro dominios y geometría electrónica tetraédrica, pero geometría molecular piramidal trigonal.</p><p>La notación <strong>AXₘEₙ</strong> resume el conteo: A es el centro, X los átomos enlazados y E los pares libres del átomo central. Esta notación se asigna después de construir correctamente Lewis.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='trepev-y-dominios-electronicos' and position('data-cbc-expansion="20260915-u4-01"' in body_html)=0;

update public.course_sections set body_html=replace(body_html,'<p>]</p>','')||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-02"><h3>De la cantidad de dominios a la forma</h3><p>Con <strong>2 dominios</strong> la máxima separación se logra a 180° y la geometría electrónica es lineal. Con <strong>3 dominios</strong> se ubican en un plano a 120°. Con <strong>4 dominios</strong> apuntan hacia los vértices de un tetraedro, con ángulo ideal de 109,5°.</p><p>Para cinco dominios aparece la <strong>bipirámide trigonal</strong>: tres posiciones ecuatoriales separadas 120° y dos axiales a 90° del plano. Para seis dominios aparece la <strong>geometría octaédrica</strong>, con direcciones a 90°.</p><p>Cuando existen pares libres, la geometría molecular cambia aunque la geometría electrónica conserve el arreglo base. Por eso <strong>AX₄</strong> es tetraédrica, <strong>AX₃E</strong> es piramidal trigonal y <strong>AX₂E₂</strong> es angular.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='geometrias-fundamentales' and position('data-cbc-expansion="20260915-u4-02"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-03"><h3>Por qué un par libre “ocupa más lugar”</h3><p>Un <strong>par libre</strong> está atraído por un solo núcleo, mientras que un par enlazante se encuentra compartido entre dos núcleos. La nube electrónica del par libre queda, en promedio, más concentrada alrededor del átomo central y ejerce una repulsión mayor sobre los otros dominios.</p><p>Por eso el orden cualitativo es <strong>PL–PL &gt; PL–PE &gt; PE–PE</strong>. Al aumentar la cantidad de pares libres, los ángulos entre enlaces suelen comprimirse. El paso CH₄ → NH₃ → H₂O permite ver la tendencia 109,5° → ~107° → ~104,5°.</p><p>Estos valores son referencias útiles, no constantes universales para cualquier AX₃E o AX₂E₂: el ángulo real también depende de los átomos enlazados y de la distribución electrónica concreta.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='efecto-de-los-pares-libres' and position('data-cbc-expansion="20260915-u4-03"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-04"><h3>La polaridad es un problema vectorial</h3><p>Una molécula será <strong>polar</strong> si la suma vectorial de todos sus momentos dipolares no es cero. Por eso el procedimiento correcto es: identificar enlaces polares, determinar la <strong>geometría real</strong>, dibujar los vectores y analizar si la simetría permite cancelarlos.</p><p>La <strong>simetría</strong> puede volver apolar una molécula con enlaces muy polares. CO₂ es lineal y los dos dipolos se cancelan; BF₃ es trigonal plano y sus tres dipolos se cancelan; CCl₄ es tetraédrico y simétrico. En H₂O, NH₃ o CHCl₃ la distribución no permite cancelación completa y queda un <strong>momento dipolar neto</strong>.</p><aside class="examTip"><strong>No alcanza con mirar ΔEN.</strong> ΔEN informa polaridad de enlace; la forma molecular decide si esos dipolos se suman o se cancelan.</aside></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='polaridad-molecular' and position('data-cbc-expansion="20260915-u4-04"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-05"><h3>London está siempre presente</h3><p>Las <strong>fuerzas de dispersión de London</strong> aparecen porque la nube electrónica fluctúa. Durante un instante puede generarse un dipolo que induce otro en una partícula vecina. Por eso actúan en <strong>todas las partículas</strong>, incluso cuando la molécula no tiene dipolo permanente.</p><p>La intensidad crece con la <strong>polarizabilidad</strong>, es decir, con la facilidad con que se deforma la nube electrónica. En series comparables suelen ser más polarizables las especies con más electrones y mayor tamaño. La <strong>forma molecular</strong> también importa: una mayor superficie de contacto puede aumentar las interacciones de dispersión.</p><p>Esto explica por qué, dentro de una familia de sustancias apolares, el punto de ebullición puede aumentar fuertemente con el tamaño aunque todas tengan “el mismo tipo” de fuerza intermolecular.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='fuerzas-de-dispersion-de-london' and position('data-cbc-expansion="20260915-u4-05"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-06"><h3>Dipolos permanentes que se orientan</h3><p>Las interacciones <strong>dipolo–dipolo</strong> aparecen entre moléculas con <strong>momento dipolar permanente</strong>. Las orientaciones en las que un extremo δ+ queda próximo a un extremo δ− son energéticamente más favorables que las orientaciones con cargas parciales del mismo signo enfrentadas.</p><p>Una molécula polar no deja de tener London: las fuerzas son <strong>acumulativas</strong>. Por lo tanto, entre moléculas polares actúan London y dipolo–dipolo; si además existe la condición apropiada para puente de hidrógeno, también aparece esa interacción.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='interacciones-dipolo-dipolo' and position('data-cbc-expansion="20260915-u4-06"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-07"><h3>Donante y aceptor de puente de hidrógeno</h3><p>Para que exista <strong>puente de hidrógeno</strong> se necesita un H enlazado directamente a <strong>N, O o F</strong> y un átomo electronegativo con un <strong>par libre</strong> capaz de actuar como aceptor. El grupo X—H funciona como <strong>donante</strong> y el par libre de otra partícula como <strong>aceptor</strong>.</p><p>No basta con que una fórmula contenga H y O por separado. Por ejemplo, un H unido a C no se considera, en este nivel, un donante típico de puente de hidrógeno. Esta interacción ayuda a explicar los puntos de ebullición anormalmente altos de H₂O, HF y NH₃ respecto de sustancias comparables.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='puentes-de-hidrogeno' and position('data-cbc-expansion="20260915-u4-07"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-08"><h3>Qué ocurre cuando una sal entra en un solvente polar</h3><p>En una interacción <strong>ion–dipolo</strong>, una carga completa interactúa con las cargas parciales de una molécula polar. En agua, el O con δ− se orienta hacia los <strong>cationes</strong> y los H con δ+ hacia los <strong>aniones</strong>.</p><p>Varias moléculas de solvente pueden rodear a cada ion formando una <strong>capa de solvatación</strong> o, si el solvente es agua, de <strong>hidratación</strong>. Disolver una sal requiere compensar la energía necesaria para separar los iones de la red con las interacciones nuevas entre iones y solvente; por eso la regla “iónico = soluble” no es absoluta.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='interacciones-ion-dipolo' and position('data-cbc-expansion="20260915-u4-08"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-09"><h3>De la interacción microscópica a la propiedad macroscópica</h3><p>Para pasar al estado gaseoso las partículas deben separarse. Si las <strong>fuerzas intermoleculares</strong> son más intensas, se necesita más energía y, en condiciones comparables, aumenta el <strong>punto de ebullición</strong>. A la misma temperatura, una sustancia cuyas partículas se atraen con mayor intensidad suele presentar <strong>menor presión de vapor</strong> y <strong>menor volatilidad</strong>.</p><p>La comparación debe hacerse en etapas. Primero se identifica el <strong>tipo de partícula</strong>; después la polaridad y las interacciones posibles. Si dos sustancias presentan el mismo tipo dominante, recién entonces se comparan <strong>masa molar, número de electrones, polarizabilidad y forma</strong>.</p><p>En solubilidad importan las interacciones que se rompen y las que se forman. “<strong>Lo semejante disuelve a lo semejante</strong>” resume que solvente y soluto deben poder establecer interacciones favorables de magnitud suficiente, pero no reemplaza el análisis químico.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='relacion-entre-fuerzas-y-propiedades' and position('data-cbc-expansion="20260915-u4-09"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-10"><h3>La cadena lógica completa</h3><p>Los ejercicios integradores se resuelven mejor siguiendo siempre la misma ruta: <strong>composición → Lewis → dominios → AXₘEₙ → geometría → polaridad → interacciones → propiedad</strong>. Saltar directamente a “es polar” o “tiene puente de hidrógeno” suele ocultar el paso que realmente justifica la respuesta.</p><p>Si la consigna da <strong>número atómico, protones o electrones</strong>, primero hay que identificar los elementos. Si da una fórmula, se construye Lewis y se cuentan únicamente los dominios sobre el átomo central. Después se analiza la simetría y recién entonces se decide la polaridad molecular.</p><p>Para comparar una propiedad física, no alcanza con nombrar la fuerza dominante: la conclusión debe conectarse explícitamente con la energía necesaria para separar partículas. Esa frase causal es la que transforma una respuesta memorizada en una <strong>justificación de examen</strong>.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='estrategia-integral-de-resolucion' and position('data-cbc-expansion="20260915-u4-10"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-11"><h3>Cómo asignarla sin memorizar moléculas</h3><p>En el modelo utilizado en este nivel, la <strong>hibridación</strong> se relaciona con el número de dominios alrededor del átomo central: 2 → <strong>sp</strong>, 3 → <strong>sp²</strong>, 4 → <strong>sp³</strong>, 5 → <strong>sp³d</strong> y 6 → <strong>sp³d²</strong>. Primero se cuenta; después se asigna.</p><p>Un error típico es contar un enlace doble como dos dominios. Para TRePEV y para esta asignación, cualquier enlace múltiple ocupa <strong>una sola región direccional</strong>. Los pares libres sí suman dominios aunque no aparezcan como átomos en la geometría molecular.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='hibridacion-puente-entre-lewis-y-la-geometria' and position('data-cbc-expansion="20260915-u4-11"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-12"><h3>Cómo usar el cuadro sin aprenderlo de memoria</h3><p>Las primeras tres filas salen de una única idea: maximizar la separación entre 2, 3 o 4 dominios. Las formas con E se obtienen “ocultando” los pares libres al nombrar la <strong>geometría molecular</strong>. Así, cuatro dominios generan una base tetraédrica; si uno es libre resulta AX₃E y si dos son libres resulta AX₂E₂.</p><p>En un ejercicio, escribí primero el <strong>número total de dominios</strong> y después la notación AXE. Esto reduce mucho los errores de elegir una geometría solamente por la cantidad de átomos que aparecen en la fórmula.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='cuadro-visual-trepev' and position('data-cbc-expansion="20260915-u4-12"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-13"><h3>El ranking es una orientación, no una calculadora automática</h3><p>El orden cualitativo ayuda a reconocer interacciones, pero para comparar sustancias reales hay que considerar <strong>cuántos sitios interactúan</strong>, el <strong>tamaño</strong>, la <strong>polarizabilidad</strong> y la <strong>forma</strong>. Por eso no es correcto afirmar que cualquier molécula polar hierve más alto que cualquier molécula apolar.</p><p>La justificación fuerte tiene esta estructura: “la sustancia A presenta ___; además tiene ___; por lo tanto se requiere ___ energía para separar sus partículas y se espera un punto de ebullición ___”. Esa cadena conecta <strong>estructura → interacción → energía → propiedad</strong>.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='ranking-de-interacciones-y-justificacion-de-examen' and position('data-cbc-expansion="20260915-u4-13"' in body_html)=0;

update public.course_sections set body_html=body_html||$cbc$<section class="theoryExtension" data-cbc-expansion="20260915-u4-14"><h3>Control final antes de cerrar el ejercicio</h3><p>Revisá que la <strong>Lewis</strong> use el número correcto de electrones, que la notación <strong>AXₘEₙ</strong> cuente sólo dominios del centro, que la geometría molecular ignore los pares libres al nombrar la forma y que la <strong>polaridad</strong> se justifique mediante vectores y simetría.</p><p>Al hablar de fuerzas, escribí <strong>todas las que están presentes</strong> y luego señalá cuál es la más característica para la comparación. Recordá: London siempre aparece; dipolo–dipolo requiere molécula polar; puente de hidrógeno requiere H unido a N/O/F; ion–dipolo requiere un ion y una molécula polar.</p></section>$cbc$,updated_at=now() where subject='chemistry' and unit_no=4 and section_key='protocolo-para-resolver-geometria-y-propiedades' and position('data-cbc-expansion="20260915-u4-14"' in body_html)=0;

commit;
