-- Exercise statements and protected solutions for CBC x SOLved.
create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  subject text not null default 'chemistry',
  unit_no integer not null check (unit_no between 1 and 13),
  section_key text not null,
  title text not null,
  statement_html text not null,
  source_label text,
  sort_order integer not null default 0,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(subject,unit_no,section_key,title)
);
create table if not exists public.exercise_solutions (
  exercise_id bigint primary key references public.exercises(id) on delete cascade,
  solution_html text not null,
  final_answer text,
  student_visible boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.exercises enable row level security;
alter table public.exercise_solutions enable row level security;

create or replace function public.can_access_exercise(target_id bigint)
returns boolean language sql stable security definer set search_path=public
as $$
 select public.is_cbc_admin() or exists(
   select 1 from public.exercises e
   where e.id=target_id and (
     e.is_public or public.has_active_cbc_access(e.subject,e.unit_no,'exercise',e.section_key)
     or public.has_active_cbc_access(e.subject,e.unit_no,'chapter',e.section_key)
   )
 )
$$;

drop policy if exists "read allowed exercises" on public.exercises;
drop policy if exists "admin manage exercises" on public.exercises;
create policy "read allowed exercises" on public.exercises for select to anon,authenticated
 using(is_public or public.has_active_cbc_access(subject,unit_no,'exercise',section_key)
   or public.has_active_cbc_access(subject,unit_no,'chapter',section_key));
create policy "admin manage exercises" on public.exercises for all to authenticated
 using(public.is_cbc_admin()) with check(public.is_cbc_admin());

drop policy if exists "read visible solutions" on public.exercise_solutions;
drop policy if exists "admin manage solutions" on public.exercise_solutions;
create policy "read visible solutions" on public.exercise_solutions for select to anon,authenticated
 using(public.is_cbc_admin() or (student_visible and public.can_access_exercise(exercise_id)));
create policy "admin manage solutions" on public.exercise_solutions for all to authenticated
 using(public.is_cbc_admin()) with check(public.is_cbc_admin());

create index if not exists exercises_lookup_idx on public.exercises(subject,unit_no,section_key,is_public,sort_order);
create index if not exists solutions_visibility_idx on public.exercise_solutions(student_visible,exercise_id);


