-- Unidad 3 · rediseño didáctico para clase y estudio
-- - mini-ruta de conceptos al comienzo de cada sección
-- - introducción general al enlace químico
-- - atomicidad
-- - criterio aproximado de ΔEN
-- - reglas de NOX en formato visual
-- El frontend complementa esto con u34-redesign.css/js y u3-lewis-library.js.

update course_sections set title='1. Enlace químico: qué es y por qué se forma' where subject='chemistry' and unit_no=3 and section_key='por-que-se-enlazan-los-atomos';
update course_sections set title='12. Control antes de entregar' where subject='chemistry' and unit_no=3 and section_key='tip-de-examen-unidad-3';
update course_sections set title='13. Mapa de compuestos inorgánicos' where subject='chemistry' and unit_no=3 and section_key='mapa-conceptual-compuestos-inorganicos';
update course_sections set title='14. Estructuras de Lewis: método y biblioteca' where subject='chemistry' and unit_no=3 and section_key='guia-lewis-obligatoria-para-los-ejercicios-4-7-4-10';

update course_sections
set body_html = $$<section class="conceptIntro" data-u34-detail="u3-bond-intro"><h3>¿Qué es un enlace químico?</h3><div class="definitionCard"><p>Un <strong>enlace químico</strong> es una interacción que mantiene unidos átomos o iones porque la especie formada puede quedar a <strong>menor energía</strong> que las partículas separadas.</p></div><p>En esta unidad trabajamos los <strong>enlaces de primer orden</strong>: <strong>iónico</strong>, <strong>covalente</strong> y <strong>metálico</strong>. En los tres casos participan principalmente los <strong>electrones de valencia</strong>.</p><p>La configuración electrónica ayuda a entender qué electrones están disponibles para enlazar. En muchos elementos representativos, perder, ganar o compartir electrones conduce a una <strong>capa de valencia completa</strong> o a subniveles externos especialmente estables. Esa relación explica por qué la regla del octeto funciona muchas veces, aunque la causa física del enlace sigue siendo la disminución de energía del sistema.</p><figure class="inlineStudyVisual"><img src="./assets/chemistry/unit-03/bond-types-overview.svg" alt="Comparación entre enlace covalente, iónico y metálico"><figcaption>Los tres enlaces de primer orden que se trabajan en la Unidad 3.</figcaption></figure></section>$$ || body_html
where subject='chemistry' and unit_no=3 and section_key='por-que-se-enlazan-los-atomos' and position('data-u34-detail="u3-bond-intro"' in body_html)=0;

update course_sections
set body_html = body_html || $$<section class="conceptIntro" data-u34-detail="u3-atomicity"><h3>Atomicidad</h3><div class="definitionCard"><p><strong>Atomicidad</strong> = cantidad total de átomos que forman una <strong>molécula discreta</strong>. Ejemplos: H₂ tiene atomicidad 2, H₂O atomicidad 3 y P₄ atomicidad 4.</p></div><p>La atomicidad tiene sentido cuando existe una molécula individual. En una <strong>red iónica</strong> como NaCl, una <strong>red covalente</strong> como SiO₂ o una <strong>red metálica</strong> como Cu no se cuenta una molécula aislada: la fórmula expresa composición o proporción.</p><figure class="inlineStudyVisual"><img src="./assets/chemistry/unit-03/atomicity-networks.svg" alt="Comparación entre moléculas discretas, atomicidad y redes extendidas"><figcaption>Moléculas discretas frente a redes extendidas.</figcaption></figure></section>$$
where subject='chemistry' and unit_no=3 and section_key='redes-infinitas-y-moleculas-discretas' and position('data-u34-detail="u3-atomicity"' in body_html)=0;

update course_sections
set body_html = $$<section class="conceptIntro" data-u34-detail="u3-en-scale"><h3>Criterio aproximado con ΔEN</h3><p><strong>ΔEN = |EN₁ − EN₂|</strong></p><div class="enScale"><div class="nonpolar"><b>0 a 0,4</b><span>covalente no polar o muy débilmente polar</span></div><div class="polar"><b>0,4 a 1,7</b><span>covalente polar</span></div><div class="ionic"><b>&gt; 1,7</b><span>carácter iónico predominante</span></div></div><p>Estos límites son <strong>orientativos</strong>, no fronteras físicas exactas. También hay que mirar si participan metales/no metales y qué estructura forma la sustancia.</p><figure class="inlineStudyVisual"><img src="./assets/chemistry/unit-03/electronegativity-scale.svg" alt="Escala aproximada para clasificar enlaces según diferencia de electronegatividad"><figcaption>Escala útil para clasificar rápidamente el carácter del enlace.</figcaption></figure></section>$$ || body_html
where subject='chemistry' and unit_no=3 and section_key='electronegatividad-y-clasificacion-de-enlaces' and position('data-u34-detail="u3-en-scale"' in body_html)=0;

update course_sections set body_html=replace(body_html,'<h3>Número de oxidación: una herramienta de contabilidad</h3>','<h3>Cómo se calcula</h3>') where subject='chemistry' and unit_no=3 and section_key='numero-de-oxidacion';
update course_sections set body_html=replace(body_html,'<h3>Qué significa realmente “más estable”</h3>','<h3>Estabilidad y energía</h3>') where subject='chemistry' and unit_no=3 and section_key='por-que-se-enlazan-los-atomos';
update course_sections set body_html=replace(body_html,'<h3>Cómo usar la electronegatividad sin convertirla en una regla mecánica</h3>','<h3>Diferencia de electronegatividad</h3>') where subject='chemistry' and unit_no=3 and section_key='electronegatividad-y-clasificacion-de-enlaces';
update course_sections set body_html=replace(body_html,'<h3>Los tres controles que evitan casi todos los errores</h3>','<h3>Control de una estructura de Lewis</h3>') where subject='chemistry' and unit_no=3 and section_key='metodo-para-dibujar-estructuras-de-lewis';

update course_sections
set body_html = (case section_key
when 'por-que-se-enlazan-los-atomos' then $$<section class="chapterOverview" data-chapter-overview="u3-01"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">enlace químico</span><span class="conceptArrow">→</span><span class="conceptKey">electrones de valencia</span><span class="conceptArrow">→</span><span class="conceptKey">menor energía</span><span class="conceptArrow">→</span><span class="conceptKey">iónico · covalente · metálico</span></div></section>$$
when 'redes-infinitas-y-moleculas-discretas' then $$<section class="chapterOverview" data-chapter-overview="u3-02"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">partícula</span><span class="conceptArrow">→</span><span class="conceptKey">molécula discreta</span><span class="conceptArrow">→</span><span class="conceptKey">atomicidad</span><span class="conceptArrow">/</span><span class="conceptKey">red extendida</span><span class="conceptArrow">→</span><span class="conceptKey">unidad fórmula</span></div></section>$$
when 'electronegatividad-y-clasificacion-de-enlaces' then $$<section class="chapterOverview" data-chapter-overview="u3-03"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">electronegatividad</span><span class="conceptArrow">→</span><span class="conceptKey">ΔEN</span><span class="conceptArrow">→</span><span class="conceptKey">no polar</span><span class="conceptArrow">→</span><span class="conceptKey">polar</span><span class="conceptArrow">→</span><span class="conceptKey">carácter iónico</span></div></section>$$
when 'enlace-ionico' then $$<section class="chapterOverview" data-chapter-overview="u3-04"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">metal pierde e⁻</span><span class="conceptArrow">→</span><span class="conceptKey">catión</span><span class="conceptArrow">+</span><span class="conceptKey">anión</span><span class="conceptArrow">→</span><span class="conceptKey">red iónica</span></div></section>$$
when 'enlace-covalente-y-estructuras-de-lewis' then $$<section class="chapterOverview" data-chapter-overview="u3-05"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">compartir pares</span><span class="conceptArrow">→</span><span class="conceptKey">simple · doble · triple</span><span class="conceptArrow">→</span><span class="conceptKey">Lewis</span><span class="conceptArrow">→</span><span class="conceptKey">resonancia</span></div></section>$$
when 'metodo-para-dibujar-estructuras-de-lewis' then $$<section class="chapterOverview" data-chapter-overview="u3-06"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">contar e⁻</span><span class="conceptArrow">→</span><span class="conceptKey">esqueleto</span><span class="conceptArrow">→</span><span class="conceptKey">octetos</span><span class="conceptArrow">→</span><span class="conceptKey">carga formal</span></div></section>$$
when 'regla-del-octeto-y-excepciones' then $$<section class="chapterOverview" data-chapter-overview="u3-07"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">dueto</span><span class="conceptArrow">·</span><span class="conceptKey">octeto</span><span class="conceptArrow">→</span><span class="conceptKey">incompleto · impar · expandido</span></div></section>$$
when 'enlace-metalico' then $$<section class="chapterOverview" data-chapter-overview="u3-08"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">red metálica</span><span class="conceptArrow">→</span><span class="conceptKey">e⁻ deslocalizados</span><span class="conceptArrow">→</span><span class="conceptKey">conductividad · maleabilidad</span></div></section>$$
when 'polaridad-de-enlace-y-momento-dipolar' then $$<section class="chapterOverview" data-chapter-overview="u3-09"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">ΔEN</span><span class="conceptArrow">→</span><span class="conceptKey">δ⁺ / δ⁻</span><span class="conceptArrow">→</span><span class="conceptKey">μ = |q|·d</span></div></section>$$
when 'numero-de-oxidacion' then $$<section class="chapterOverview" data-chapter-overview="u3-10"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">reglas de NOX</span><span class="conceptArrow">→</span><span class="conceptKey">Σ NOX = carga</span><span class="conceptArrow">→</span><span class="conceptKey">despejar x</span></div></section>$$
when 'clasificacion-y-nomenclatura-de-compuestos-inorganicos' then $$<section class="chapterOverview" data-chapter-overview="u3-11"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">familia</span><span class="conceptArrow">→</span><span class="conceptKey">NOX</span><span class="conceptArrow">→</span><span class="conceptKey">formular / nombrar</span></div></section>$$
when 'tip-de-examen-unidad-3' then $$<section class="chapterOverview" data-chapter-overview="u3-12"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">criterio</span><span class="conceptArrow">→</span><span class="conceptKey">planteo</span><span class="conceptArrow">→</span><span class="conceptKey">desarrollo</span><span class="conceptArrow">→</span><span class="conceptKey">resultado</span></div></section>$$
when 'mapa-conceptual-compuestos-inorganicos' then $$<section class="chapterOverview" data-chapter-overview="u3-13"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">elemento</span><span class="conceptArrow">→</span><span class="conceptKey">óxido</span><span class="conceptArrow">→</span><span class="conceptKey">hidróxido / ácido</span><span class="conceptArrow">→</span><span class="conceptKey">sal</span></div></section>$$
when 'guia-lewis-obligatoria-para-los-ejercicios-4-7-4-10' then $$<section class="chapterOverview" data-chapter-overview="u3-14"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">e⁻ de valencia</span><span class="conceptArrow">→</span><span class="conceptKey">estructura</span><span class="conceptArrow">→</span><span class="conceptKey">carga formal</span><span class="conceptArrow">→</span><span class="conceptKey">resonancia</span></div></section>$$ else '' end) || body_html
where subject='chemistry' and unit_no=3 and position('data-chapter-overview=' in body_html)=0;
