-- Unidad 4 · rediseño didáctico para clase y estudio
-- - mini-ruta de conceptos al comienzo de cada sección
-- - títulos más directos
-- - apoyo visual de interacciones y propiedades
-- El frontend complementa esto con u34-redesign.css/js.

update course_sections set title='10. De Lewis a las propiedades' where subject='chemistry' and unit_no=4 and section_key='estrategia-integral-de-resolucion';
update course_sections set title='11. Hibridación y geometría' where subject='chemistry' and unit_no=4 and section_key='hibridacion-puente-entre-lewis-y-la-geometria';
update course_sections set title='13. Comparación de interacciones' where subject='chemistry' and unit_no=4 and section_key='ranking-de-interacciones-y-justificacion-de-examen';
update course_sections set title='14. Guía para resolver geometría y propiedades' where subject='chemistry' and unit_no=4 and section_key='protocolo-para-resolver-geometria-y-propiedades';

update course_sections set body_html=replace(body_html,'<h3>La cadena lógica completa</h3>','<h3>Resolución integrada</h3>') where subject='chemistry' and unit_no=4 and section_key='estrategia-integral-de-resolucion';
update course_sections set body_html=replace(body_html,'<h3>El ranking es una orientación, no una calculadora automática</h3>','<h3>Comparación entre interacciones</h3>') where subject='chemistry' and unit_no=4 and section_key='ranking-de-interacciones-y-justificacion-de-examen';
update course_sections set body_html=replace(body_html,'<h3>Control final antes de cerrar el ejercicio</h3>','<h3>Control final</h3>') where subject='chemistry' and unit_no=4 and section_key='protocolo-para-resolver-geometria-y-propiedades';

update course_sections
set body_html = body_html || $$<figure class="inlineStudyVisual" data-u34-detail="u4-interactions-visual"><img src="./assets/chemistry/unit-04/interactions-roadmap.svg" alt="Ruta desde el tipo de partícula hasta las fuerzas intermoleculares y las propiedades"><figcaption>Ruta de análisis: partícula → polaridad → interacción → propiedad.</figcaption></figure>$$
where subject='chemistry' and unit_no=4 and section_key='relacion-entre-fuerzas-y-propiedades' and position('data-u34-detail="u4-interactions-visual"' in body_html)=0;

update course_sections
set body_html = (case section_key
when 'trepev-y-dominios-electronicos' then $$<section class="chapterOverview" data-chapter-overview="u4-01"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">Lewis</span><span class="conceptArrow">→</span><span class="conceptKey">dominios electrónicos</span><span class="conceptArrow">→</span><span class="conceptKey">AXₘEₙ</span><span class="conceptArrow">→</span><span class="conceptKey">geometría</span></div></section>$$
when 'geometrias-fundamentales' then $$<section class="chapterOverview" data-chapter-overview="u4-02"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">2: lineal</span><span class="conceptArrow">→</span><span class="conceptKey">3: trigonal plana</span><span class="conceptArrow">→</span><span class="conceptKey">4: tetraédrica</span><span class="conceptArrow">→</span><span class="conceptKey">5 / 6 dominios</span></div></section>$$
when 'efecto-de-los-pares-libres' then $$<section class="chapterOverview" data-chapter-overview="u4-03"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">pares libres</span><span class="conceptArrow">→</span><span class="conceptKey">mayor repulsión</span><span class="conceptArrow">→</span><span class="conceptKey">menor ángulo</span></div></section>$$
when 'polaridad-molecular' then $$<section class="chapterOverview" data-chapter-overview="u4-04"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">enlace polar</span><span class="conceptArrow">+</span><span class="conceptKey">geometría</span><span class="conceptArrow">→</span><span class="conceptKey">suma vectorial</span><span class="conceptArrow">→</span><span class="conceptKey">μ total</span></div></section>$$
when 'fuerzas-de-dispersion-de-london' then $$<section class="chapterOverview" data-chapter-overview="u4-05"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">dipolo instantáneo</span><span class="conceptArrow">→</span><span class="conceptKey">dipolo inducido</span><span class="conceptArrow">→</span><span class="conceptKey">London</span><span class="conceptArrow">→</span><span class="conceptKey">polarizabilidad</span></div></section>$$
when 'interacciones-dipolo-dipolo' then $$<section class="chapterOverview" data-chapter-overview="u4-06"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">molécula polar</span><span class="conceptArrow">→</span><span class="conceptKey">dipolo permanente</span><span class="conceptArrow">→</span><span class="conceptKey">dipolo–dipolo</span><span class="conceptArrow">+</span><span class="conceptKey">London</span></div></section>$$
when 'puentes-de-hidrogeno' then $$<section class="chapterOverview" data-chapter-overview="u4-07"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">H—N / H—O / H—F</span><span class="conceptArrow">→</span><span class="conceptKey">donante</span><span class="conceptArrow">+</span><span class="conceptKey">aceptor</span><span class="conceptArrow">→</span><span class="conceptKey">puente de H</span></div></section>$$
when 'interacciones-ion-dipolo' then $$<section class="chapterOverview" data-chapter-overview="u4-08"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">ion</span><span class="conceptArrow">+</span><span class="conceptKey">molécula polar</span><span class="conceptArrow">→</span><span class="conceptKey">orientación</span><span class="conceptArrow">→</span><span class="conceptKey">solvatación</span></div></section>$$
when 'relacion-entre-fuerzas-y-propiedades' then $$<section class="chapterOverview" data-chapter-overview="u4-09"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">interacción</span><span class="conceptArrow">→</span><span class="conceptKey">energía</span><span class="conceptArrow">→</span><span class="conceptKey">Teb · Pvap · volatilidad · solubilidad</span></div></section>$$
when 'estrategia-integral-de-resolucion' then $$<section class="chapterOverview" data-chapter-overview="u4-10"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">Lewis</span><span class="conceptArrow">→</span><span class="conceptKey">geometría</span><span class="conceptArrow">→</span><span class="conceptKey">polaridad</span><span class="conceptArrow">→</span><span class="conceptKey">fuerza</span><span class="conceptArrow">→</span><span class="conceptKey">propiedad</span></div></section>$$
when 'hibridacion-puente-entre-lewis-y-la-geometria' then $$<section class="chapterOverview" data-chapter-overview="u4-11"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">dominios</span><span class="conceptArrow">→</span><span class="conceptKey">sp · sp² · sp³</span><span class="conceptArrow">→</span><span class="conceptKey">geometría</span></div></section>$$
when 'cuadro-visual-trepev' then $$<section class="chapterOverview" data-chapter-overview="u4-12"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">AXₘEₙ</span><span class="conceptArrow">→</span><span class="conceptKey">forma</span><span class="conceptArrow">→</span><span class="conceptKey">ángulo</span><span class="conceptArrow">→</span><span class="conceptKey">ejemplo</span></div></section>$$
when 'ranking-de-interacciones-y-justificacion-de-examen' then $$<section class="chapterOverview" data-chapter-overview="u4-13"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">interacción</span><span class="conceptArrow">+</span><span class="conceptKey">tamaño</span><span class="conceptArrow">+</span><span class="conceptKey">polarizabilidad</span><span class="conceptArrow">+</span><span class="conceptKey">forma</span></div></section>$$
when 'protocolo-para-resolver-geometria-y-propiedades' then $$<section class="chapterOverview" data-chapter-overview="u4-14"><h3>Conceptos de este tema</h3><div class="conceptPath"><span class="conceptKey">Planteo</span><span class="conceptArrow">→</span><span class="conceptKey">fórmulas / criterio</span><span class="conceptArrow">→</span><span class="conceptKey">Desarrollo</span><span class="conceptArrow">→</span><span class="conceptKey">Resultado</span></div></section>$$ else '' end) || body_html
where subject='chemistry' and unit_no=4 and position('data-chapter-overview=' in body_html)=0;
